### ISSUE TITLE
希望鼠标右键能取消截图

### ISSUE THREAD

**Issue by Gszekt** [easysoft/zenshot#11]
步骤：
1. 启动截图
2. 鼠标悬浮到应用（比如浏览器）上
3. 单击鼠标右键
现在的逻辑是鼠标点击了左键，右键，中键，前进键都会触发截图，
希望将右键改为取消截图，中键，前进键，后退键可以改为不触发截图或者绑定其它功能

**Comment by wwccss** [comment]
我们复现了，正在检查修复。谢谢反馈。
