### ISSUE TITLE
编译错误问题

### ISSUE THREAD

**Issue by wey580231** [easysoft/zenshot#15]
使用Qt5.10+vs2015编译出现大量莫名的错误，是编译器不对么？

![image](https://user-images.githubusercontent.com/13130262/229095521-16492004-0b41-4d7c-9b06-67cb0ee634d5.png)

**Comment by illusionlee** [comment]
请尝试一下使用QtCreator+MinGW_32进行编译。我自己使用了 build-zenshot-Desktop_Qt_5_15_2_MinGW_32_bit-Release 能够正常编译运行。

**Comment by wey580231** [comment]
多谢！因项目编译环境的要求，后来我重新建立了一个工程，把代码逐一移植过去后，重新编译就行。

**Comment by illusionlee** [comment]
很高兴你能够成功跑通，后面有什么建议欢迎反馈 ;)
