### ISSUE TITLE
构建错误: User32.lib: No such file or directory

### ISSUE THREAD

**Issue by icanpool** [easysoft/zenshot#17]
系统：Windows 10.0.18363.1556
Qt：5.14.2
构建错误：
![image](https://github.com/easysoft/zenshot/assets/75650733/9368f5bb-31e8-436d-8830-ef057879e21d)

解决方法：
将```LIBS    += User32.lib``` 改为 ```LIBS    += -lUser32``` 可构建成功

**Comment by illusionlee** [comment]
非常感谢你的反馈！
